name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-and-lint:
    name: Build, Lint & Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go: ['1.22', '1.23']

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: ${{ matrix.go }}

      - name: Verify Code Formatting
        run: |
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
            echo "The following files are not formatted properly:"
            gofmt -s -l .
            exit 1
          fi

      - name: Run Go Vet
        run: go vet ./...

      - name: Run Unit Tests with Race Detector
        run: go test -v -race "-coverprofile=coverage.out" ./...

      - name: Build Binary
        run: go build -v ./cmd/file-watcher

